### ISSUE TITLE
Docker-py dependecies

### ISSUE THREAD

**Issue by ikus060** [grycap/ansible-role-docker#18]
While using this playbook, I'm expecting the installation of docker-py to be part of it. 
I see a commit that include the installation of that dependency, but it's not included in master or was reverted back.
https://github.com/grycap/ansible-role-docker/commit/35d113cb227b86cf4c5f630069d2b56f32c85b81

**Comment by micafer** [comment]
Hi @ikus060 we have added again the installation of docker-py as it is an interesting feature.
