### ISSUE TITLE
/etc/default/docker configuration file does not work in Ubuntu 16

### ISSUE THREAD

**Issue by iblanque** [grycap/ansible-role-docker#8]
Hi,

I realized that the file /etc/default/docker does not work in Ubuntu 16, as it uses systemd, which ignores this file.

It is recommended to use the /etc/docker/daemon.json configuration file, which is agnostic of the system. Documentation in https://docs.docker.com/engine/reference/commandline/dockerd//#daemon-configuration-file 

Thanks!

**Comment by micafer** [comment]
Hi @iblanque,

We found an error in the tasks using an incorrect ansible var name that causes that it does not load correcltly the DOCKER_OPTS in Ubuntu 16-
We have fixed with this commit: b06109d32d0286f677e4b32ade4b8ca2773c43e5

Could you test it please?
